---
title: "project_2"
subtitle: Project 2 Analysis
date: "`r Sys.Date()`"
output: 
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE, message=FALSE}
library(tidyverse)
library(stargazer) 
library(sandwich)
library(ggplot2)
```

```{r, exploratory data analysis}
#import file
df <- read.csv('./movies.csv')

#reformat fields
df$release_date <- as.Date(df$release_date, format = "%Y-%m-%d")
df$release_year <- format(df$release_date, format = "%Y")
df$budget <- as.numeric(df$budget)
df$revenue <- as.numeric(df$revenue)

#select the fields we care about for our analysis
df <- df %>% select(budget, genres, release_year, revenue, title)

#made an assumption that any movie before 2000 is irrelevant and not applicable for our analysis
#removing any data points with 0 budget and revenue as they are not applicable
df <- filter(df, release_year >= "2000" & (budget > 0 & revenue > 0))

#group data by release year
df_by_year <- df %>% group_by(release_year)

#bar graph to see the number of data points
p <- ggplot(data=df_by_year, aes(x=release_year))+
  geom_bar()+
  theme(axis.text.x = element_text(angle=45))
p

#based on the graph, 2011 is the year with the most data points 
df_2011 <- filter(df, release_year == "2011") 
        
```

```{r, genres}
str_extract(df_2011$genres, "|:[a-z]+")
#strsplit(df_2011$genres, split = c(",", ":"))

```

```{r, profit}
df_2011$profit = df_2011$revenue - df_2011$budget

```


